# golangci-lint configuration for go-config (v2 format)
# Based on Some Things To Do monorepo standards

version: "2"

run:
  # Timeout for analysis - prevents CI hangs while allowing thorough checking
  timeout: 5m

linters:
  default: none
  enable:
    - govet
    - staticcheck
    - ineffassign
    - misspell
    - unconvert
    - gosec

  settings:
    staticcheck:
      checks: ["all"]

    gosec:
      # Exclude specific rules that are problematic in test contexts
      excludes:
        - G104  # Unhandled errors - common in test files for os.Setenv/Unsetenv
        - G306  # File permissions - test files create temporary files with standard 0o644 permissions

  exclusions:
    paths:
      - ".*\\.pb\\.go$"
      - ".*_gen\\.go$"
      - ".*_generated\\.go$"

formatters:
  enable:
    - gofmt
    - gofumpt       # Stricter formatting than gofmt
    - goimports

  exclusions:
    paths:
      - ".*\\.pb\\.go$"
      - ".*_gen\\.go$"
      - ".*_generated\\.go$"

issues:
  # Maximum issues count per one linter
  max-issues-per-linter: 50

  # Maximum count of issues with the same text
  max-same-issues: 10
